-- Camply fresh install script
-- Generated by concatenating migration files 00..17 in order.
-- Use this file for a brand-new Supabase project.


-- ==================================================
-- BEGIN sql/00_schema.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- Camply — Schéma Supabase
-- À coller dans : Supabase Dashboard > SQL Editor > New query
-- ══════════════════════════════════════════════════════════════


-- ── 1. Table profiles ─────────────────────────────────────────
-- Créée automatiquement à chaque inscription via un trigger.
-- Liée à auth.users (UUID Supabase Auth).

CREATE TABLE IF NOT EXISTS public.profiles (
  id         UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username   TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger : crée automatiquement un profil à l'inscription
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1))
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ── 2. Table characters ───────────────────────────────────────
-- Chaque personnage appartient à un utilisateur (user_id).
-- Les données du personnage sont stockées en JSONB (data).
-- is_public = true permet le partage via lien.

CREATE TABLE IF NOT EXISTS public.characters (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name       TEXT NOT NULL DEFAULT '',
  rank       SMALLINT NOT NULL DEFAULT 5,
  is_public  BOOLEAN NOT NULL DEFAULT FALSE,
  data       JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index pour retrouver rapidement les personnages d'un utilisateur
CREATE INDEX IF NOT EXISTS characters_user_id_idx ON public.characters(user_id);
-- Index pour les personnages publics
CREATE INDEX IF NOT EXISTS characters_public_idx ON public.characters(is_public) WHERE is_public = TRUE;

-- Trigger : met à jour updated_at automatiquement
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_characters_updated ON public.characters;
CREATE TRIGGER on_characters_updated
  BEFORE UPDATE ON public.characters
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


-- ── 3. Row Level Security (RLS) ───────────────────────────────
-- RLS activé sur les deux tables.

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.characters ENABLE ROW LEVEL SECURITY;

-- profiles : chaque utilisateur lit et modifie uniquement son profil
DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
CREATE POLICY "profiles_select_own"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

-- characters : lecture
--   → ses propres personnages (privés ou publics)
--   → les personnages publics d'autrui
DROP POLICY IF EXISTS "characters_select" ON public.characters;
CREATE POLICY "characters_select"
  ON public.characters FOR SELECT
  USING (
    auth.uid() = user_id       -- propriétaire
    OR is_public = TRUE        -- ou partagé publiquement
  );

-- characters : insertion uniquement pour soi-même
DROP POLICY IF EXISTS "characters_insert" ON public.characters;
CREATE POLICY "characters_insert"
  ON public.characters FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- characters : modification
--   → propriétaire
--   → ou utilisateur abonné au personnage via followed_characters
--     (utilisé pour permettre l'édition depuis le système de partage)
DROP POLICY IF EXISTS "characters_update" ON public.characters;
CREATE POLICY "characters_update"
  ON public.characters FOR UPDATE
  USING (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1
      FROM public.followed_characters fc
      WHERE fc.character_id = characters.id
        AND fc.user_id = auth.uid()
    )
  );

-- characters : suppression uniquement de ses propres personnages
DROP POLICY IF EXISTS "characters_delete" ON public.characters;
CREATE POLICY "characters_delete"
  ON public.characters FOR DELETE
  USING (auth.uid() = user_id);


-- ── 4. Accès public en lecture seule aux personnages publics ──
-- Permet aux utilisateurs non connectés de voir un personnage
-- partagé via lien (is_public = true), sans compte requis.

DROP POLICY IF EXISTS "characters_select_public_anon" ON public.characters;
CREATE POLICY "characters_select_public_anon"
  ON public.characters FOR SELECT
  TO anon
  USING (is_public = TRUE);


-- ══════════════════════════════════════════════════════════════
-- C'est tout ! Les tables sont prêtes.
-- Retournez dans l'application pour tester l'inscription.
-- ══════════════════════════════════════════════════════════════

-- END sql/00_schema.sql

-- ==================================================
-- BEGIN sql/01_tags.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- Camply — Système de tags
-- À coller dans : Supabase Dashboard > SQL Editor > New query
-- ══════════════════════════════════════════════════════════════

-- ── 1. Table tags ─────────────────────────────────────────────
-- Un tag appartient à un utilisateur et a un nom unique par user.

CREATE TABLE IF NOT EXISTS public.tags (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  color      TEXT NOT NULL DEFAULT '#5c6070',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, name)   -- un utilisateur ne peut pas avoir deux tags du même nom
);

CREATE INDEX IF NOT EXISTS tags_user_id_idx ON public.tags(user_id);


-- ── 2. Table character_tags (liaison) ─────────────────────────

CREATE TABLE IF NOT EXISTS public.character_tags (
  character_id UUID NOT NULL REFERENCES public.characters(id) ON DELETE CASCADE,
  tag_id       UUID NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (character_id, tag_id)
);

CREATE INDEX IF NOT EXISTS character_tags_character_idx ON public.character_tags(character_id);
CREATE INDEX IF NOT EXISTS character_tags_tag_idx ON public.character_tags(tag_id);


-- ── 3. RLS ────────────────────────────────────────────────────

ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.character_tags ENABLE ROW LEVEL SECURITY;

-- Tags : lecture, création, modification, suppression = propriétaire uniquement
DROP POLICY IF EXISTS "tags_select_own" ON public.tags;
CREATE POLICY "tags_select_own" ON public.tags FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "tags_insert_own" ON public.tags;
CREATE POLICY "tags_insert_own" ON public.tags FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "tags_update_own" ON public.tags;
CREATE POLICY "tags_update_own" ON public.tags FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "tags_delete_own" ON public.tags;
CREATE POLICY "tags_delete_own" ON public.tags FOR DELETE USING (auth.uid() = user_id);

-- character_tags : accessible si le personnage appartient à l'utilisateur
DROP POLICY IF EXISTS "character_tags_select" ON public.character_tags;
CREATE POLICY "character_tags_select" ON public.character_tags FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.characters c
    WHERE c.id = character_id AND c.user_id = auth.uid()
  ));

DROP POLICY IF EXISTS "character_tags_insert" ON public.character_tags;
CREATE POLICY "character_tags_insert" ON public.character_tags FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.characters c
    WHERE c.id = character_id AND c.user_id = auth.uid()
  ));

DROP POLICY IF EXISTS "character_tags_delete" ON public.character_tags;
CREATE POLICY "character_tags_delete" ON public.character_tags FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM public.characters c
    WHERE c.id = character_id AND c.user_id = auth.uid()
  ));

-- ══════════════════════════════════════════════════════════════

-- END sql/01_tags.sql

-- ==================================================
-- BEGIN sql/02_followed.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- Camply — Partage de personnages entre membres
-- À coller dans : Supabase Dashboard > SQL Editor > New query
-- ══════════════════════════════════════════════════════════════

-- ── 1. Colonne share_code sur characters ──────────────────────

ALTER TABLE public.characters
  ADD COLUMN IF NOT EXISTS share_code TEXT UNIQUE;

UPDATE public.characters
  SET share_code = upper(substr(md5(random()::text), 1, 8))
  WHERE share_code IS NULL;

CREATE OR REPLACE FUNCTION public.generate_share_code()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  new_code TEXT;
  done BOOL := FALSE;
BEGIN
  WHILE NOT done LOOP
    new_code := upper(substr(md5(random()::text), 1, 8));
    done := TRUE;
    BEGIN
      NEW.share_code := new_code;
    EXCEPTION WHEN unique_violation THEN
      done := FALSE;
    END;
  END LOOP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_share_code ON public.characters;
CREATE TRIGGER set_share_code
  BEFORE INSERT ON public.characters
  FOR EACH ROW
  WHEN (NEW.share_code IS NULL)
  EXECUTE FUNCTION public.generate_share_code();


-- ── 2. Table followed_characters ─────────────────────────────

CREATE TABLE IF NOT EXISTS public.followed_characters (
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  character_id UUID NOT NULL REFERENCES public.characters(id) ON DELETE CASCADE,
  followed_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, character_id)
);

CREATE INDEX IF NOT EXISTS followed_user_idx
  ON public.followed_characters(user_id);


-- ── 3. RLS ────────────────────────────────────────────────────

ALTER TABLE public.followed_characters ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "followed_select_own" ON public.followed_characters;
CREATE POLICY "followed_select_own"
  ON public.followed_characters FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "followed_insert_own" ON public.followed_characters;
CREATE POLICY "followed_insert_own"
  ON public.followed_characters FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "followed_delete_own" ON public.followed_characters;
CREATE POLICY "followed_delete_own"
  ON public.followed_characters FOR DELETE
  USING (auth.uid() = user_id);

-- END sql/02_followed.sql

-- ==================================================
-- BEGIN sql/03_chronicles.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- Camply — Chroniques v2 (migration incluse)
-- À coller dans : Supabase Dashboard > SQL Editor > New query
-- ══════════════════════════════════════════════════════════════

-- ── 1. Nettoyage de l'ancien schéma ───────────────────────────

DROP TABLE IF EXISTS public.followed_chronicles CASCADE;
DROP TABLE IF EXISTS public.chronicles CASCADE;


-- ── 2. Table chronicles ───────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.chronicles (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id              UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title                TEXT NOT NULL DEFAULT '',
  description          TEXT NOT NULL DEFAULT '',
  is_public            BOOLEAN NOT NULL DEFAULT FALSE,
  share_code           TEXT UNIQUE,
  illustration_url     TEXT NOT NULL DEFAULT '',
  illustration_position SMALLINT NOT NULL DEFAULT 0,
  created_at           TIMESTAMPTZ DEFAULT NOW(),
  updated_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS chronicles_user_id_idx ON public.chronicles(user_id);
CREATE INDEX IF NOT EXISTS chronicles_public_idx  ON public.chronicles(is_public) WHERE is_public = TRUE;

DROP TRIGGER IF EXISTS on_chronicles_updated ON public.chronicles;
CREATE TRIGGER on_chronicles_updated
  BEFORE UPDATE ON public.chronicles
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_chronicle_share_code ON public.chronicles;
CREATE TRIGGER set_chronicle_share_code
  BEFORE INSERT ON public.chronicles
  FOR EACH ROW
  WHEN (NEW.share_code IS NULL)
  EXECUTE FUNCTION public.generate_share_code();


-- ── 3. Table chronicle_entries ────────────────────────────────

CREATE TABLE IF NOT EXISTS public.chronicle_entries (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chronicle_id UUID NOT NULL REFERENCES public.chronicles(id) ON DELETE CASCADE,
  title        TEXT NOT NULL DEFAULT '',
  content      TEXT NOT NULL DEFAULT '',
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS entries_chronicle_id_idx ON public.chronicle_entries(chronicle_id);

DROP TRIGGER IF EXISTS on_entries_updated ON public.chronicle_entries;
CREATE TRIGGER on_entries_updated
  BEFORE UPDATE ON public.chronicle_entries
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE OR REPLACE FUNCTION public.handle_entry_updated()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  UPDATE public.chronicles SET updated_at = NOW() WHERE id = NEW.chronicle_id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_entry_touch_chronicle ON public.chronicle_entries;
CREATE TRIGGER on_entry_touch_chronicle
  AFTER INSERT OR UPDATE ON public.chronicle_entries
  FOR EACH ROW EXECUTE FUNCTION public.handle_entry_updated();


-- ── 4. Table followed_chronicles ──────────────────────────────

CREATE TABLE IF NOT EXISTS public.followed_chronicles (
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  chronicle_id UUID NOT NULL REFERENCES public.chronicles(id) ON DELETE CASCADE,
  followed_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, chronicle_id)
);

CREATE INDEX IF NOT EXISTS followed_chronicles_user_idx ON public.followed_chronicles(user_id);


-- ── 5. RLS ────────────────────────────────────────────────────

ALTER TABLE public.chronicles          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chronicle_entries   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.followed_chronicles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "chronicles_select"      ON public.chronicles;
CREATE POLICY "chronicles_select" ON public.chronicles FOR SELECT
  USING (auth.uid() = user_id OR is_public = TRUE);

DROP POLICY IF EXISTS "chronicles_select_anon" ON public.chronicles;
CREATE POLICY "chronicles_select_anon" ON public.chronicles FOR SELECT
  TO anon USING (is_public = TRUE);

DROP POLICY IF EXISTS "chronicles_insert" ON public.chronicles;
CREATE POLICY "chronicles_insert" ON public.chronicles FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "chronicles_update" ON public.chronicles;
CREATE POLICY "chronicles_update" ON public.chronicles FOR UPDATE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "chronicles_delete" ON public.chronicles;
CREATE POLICY "chronicles_delete" ON public.chronicles FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "entries_select" ON public.chronicle_entries;
CREATE POLICY "entries_select" ON public.chronicle_entries FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.chronicles c
    WHERE c.id = chronicle_id
      AND (c.user_id = auth.uid() OR c.is_public = TRUE)
  ));

DROP POLICY IF EXISTS "entries_select_anon" ON public.chronicle_entries;
CREATE POLICY "entries_select_anon" ON public.chronicle_entries FOR SELECT
  TO anon
  USING (EXISTS (
    SELECT 1 FROM public.chronicles c
    WHERE c.id = chronicle_id AND c.is_public = TRUE
  ));

DROP POLICY IF EXISTS "entries_insert" ON public.chronicle_entries;
CREATE POLICY "entries_insert" ON public.chronicle_entries FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.chronicles c
    WHERE c.id = chronicle_id AND c.user_id = auth.uid()
  ));

DROP POLICY IF EXISTS "entries_update" ON public.chronicle_entries;
CREATE POLICY "entries_update" ON public.chronicle_entries FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM public.chronicles c
    WHERE c.id = chronicle_id AND c.user_id = auth.uid()
  ));

DROP POLICY IF EXISTS "entries_delete" ON public.chronicle_entries;
CREATE POLICY "entries_delete" ON public.chronicle_entries FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM public.chronicles c
    WHERE c.id = chronicle_id AND c.user_id = auth.uid()
  ));

DROP POLICY IF EXISTS "followed_chr_select" ON public.followed_chronicles;
CREATE POLICY "followed_chr_select" ON public.followed_chronicles FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "followed_chr_insert" ON public.followed_chronicles;
CREATE POLICY "followed_chr_insert" ON public.followed_chronicles FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "followed_chr_delete" ON public.followed_chronicles;
CREATE POLICY "followed_chr_delete" ON public.followed_chronicles FOR DELETE
  USING (auth.uid() = user_id);

-- END sql/03_chronicles.sql

-- ==================================================
-- BEGIN sql/04_documents.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- Camply — Documents
-- À coller dans : Supabase Dashboard > SQL Editor > New query
-- ══════════════════════════════════════════════════════════════

-- ── 1. Table documents ────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.documents (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title                 TEXT NOT NULL DEFAULT '',
  content               TEXT NOT NULL DEFAULT '',
  is_public             BOOLEAN NOT NULL DEFAULT FALSE,
  allow_write_share     BOOLEAN NOT NULL DEFAULT FALSE,
  share_code            TEXT UNIQUE,
  illustration_url      TEXT NOT NULL DEFAULT '',
  illustration_position SMALLINT NOT NULL DEFAULT 0,
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS documents_user_id_idx ON public.documents(user_id);
CREATE INDEX IF NOT EXISTS documents_public_idx  ON public.documents(is_public) WHERE is_public = TRUE;

DROP TRIGGER IF EXISTS on_documents_updated ON public.documents;
CREATE TRIGGER on_documents_updated
  BEFORE UPDATE ON public.documents
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_document_share_code ON public.documents;
CREATE TRIGGER set_document_share_code
  BEFORE INSERT ON public.documents
  FOR EACH ROW
  WHEN (NEW.share_code IS NULL)
  EXECUTE FUNCTION public.generate_share_code();


-- ── 2. Table followed_documents ───────────────────────────────

CREATE TABLE IF NOT EXISTS public.followed_documents (
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  document_id UUID NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
  followed_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, document_id)
);

CREATE INDEX IF NOT EXISTS followed_documents_user_idx ON public.followed_documents(user_id);

CREATE OR REPLACE FUNCTION public.guard_document_shared_update()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF auth.uid() IS DISTINCT FROM OLD.user_id THEN
    NEW.user_id := OLD.user_id;
    NEW.is_public := OLD.is_public;
    NEW.share_code := OLD.share_code;
    NEW.allow_write_share := OLD.allow_write_share;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS guard_document_shared_update ON public.documents;
CREATE TRIGGER guard_document_shared_update
  BEFORE UPDATE ON public.documents
  FOR EACH ROW
  EXECUTE FUNCTION public.guard_document_shared_update();


-- ── 3. RLS ────────────────────────────────────────────────────

ALTER TABLE public.documents          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.followed_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "documents_select"      ON public.documents;
CREATE POLICY "documents_select" ON public.documents FOR SELECT
  USING (auth.uid() = user_id OR is_public = TRUE);

DROP POLICY IF EXISTS "documents_select_anon" ON public.documents;
CREATE POLICY "documents_select_anon" ON public.documents FOR SELECT
  TO anon USING (is_public = TRUE);

DROP POLICY IF EXISTS "documents_insert" ON public.documents;
CREATE POLICY "documents_insert" ON public.documents FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "documents_update" ON public.documents;
CREATE POLICY "documents_update" ON public.documents FOR UPDATE
  USING (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1 FROM public.followed_documents fd
      WHERE fd.document_id = id AND fd.user_id = auth.uid() AND allow_write_share = TRUE
    )
  )
  WITH CHECK (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1 FROM public.followed_documents fd
      WHERE fd.document_id = id AND fd.user_id = auth.uid() AND allow_write_share = TRUE
    )
  );

DROP POLICY IF EXISTS "documents_delete" ON public.documents;
CREATE POLICY "documents_delete" ON public.documents FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "followed_doc_select" ON public.followed_documents;
CREATE POLICY "followed_doc_select" ON public.followed_documents FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "followed_doc_insert" ON public.followed_documents;
CREATE POLICY "followed_doc_insert" ON public.followed_documents FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "followed_doc_delete" ON public.followed_documents;
CREATE POLICY "followed_doc_delete" ON public.followed_documents FOR DELETE
  USING (auth.uid() = user_id);

-- ══════════════════════════════════════════════════════════════

-- END sql/04_documents.sql

-- ==================================================
-- BEGIN sql/05_document_tags.sql
-- ==================================================
-- Table des tags de documents (propres à chaque user)
create table doc_tags (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  color text not null,
  created_at timestamptz default now(),
  unique (user_id, name)
);
alter table doc_tags enable row level security;
create policy "Users manage own doc tags" on doc_tags
  for all using (auth.uid() = user_id);

-- Liaison document ↔ tag
create table document_tags (
  document_id uuid references documents(id) on delete cascade not null,
  tag_id uuid references doc_tags(id) on delete cascade not null,
  primary key (document_id, tag_id)
);
alter table document_tags enable row level security;
create policy "Users manage own document tags" on document_tags
  for all using (
    exists (
      select 1 from documents d where d.id = document_id and d.user_id = auth.uid()
    )
  );

-- Tags locaux pour documents suivis
create table followed_document_tags (
  user_id uuid references auth.users(id) on delete cascade not null,
  document_id uuid references documents(id) on delete cascade not null,
  tag_id uuid references doc_tags(id) on delete cascade not null,
  primary key (user_id, document_id, tag_id)
);
alter table followed_document_tags enable row level security;
create policy "Users manage own followed doc tags" on followed_document_tags
  for all using (auth.uid() = user_id);
-- END sql/05_document_tags.sql

-- ==================================================
-- BEGIN sql/06_storage.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- Camply — Bucket Storage pour les illustrations
-- À coller dans : Supabase Dashboard > SQL Editor > New query
-- ══════════════════════════════════════════════════════════════

-- ── 1. Créer le bucket public ─────────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'character-illustrations',
  'character-illustrations',
  true,                        -- bucket public : URLs directement accessibles
  3145728,                     -- limite 3 Mo par fichier
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO NOTHING;


-- ── 2. Politiques RLS Storage ─────────────────────────────────

-- Lecture publique : tout le monde peut voir les images
DROP POLICY IF EXISTS "illustrations_public_read" ON storage.objects;
CREATE POLICY "illustrations_public_read"
  ON storage.objects FOR SELECT
  TO public
  USING (bucket_id = 'character-illustrations');

-- Upload : uniquement les utilisateurs connectés,
-- dans leur propre dossier (user_id/)
DROP POLICY IF EXISTS "illustrations_insert_own" ON storage.objects;
CREATE POLICY "illustrations_insert_own"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'character-illustrations'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Remplacement : un utilisateur peut remplacer ses propres images
DROP POLICY IF EXISTS "illustrations_update_own" ON storage.objects;
CREATE POLICY "illustrations_update_own"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'character-illustrations'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Suppression : un utilisateur peut supprimer ses propres images
DROP POLICY IF EXISTS "illustrations_delete_own" ON storage.objects;
CREATE POLICY "illustrations_delete_own"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'character-illustrations'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- ══════════════════════════════════════════════════════════════
-- Les images seront stockées sous la forme :
-- character-illustrations/{user_id}/{character_id}.{ext}
-- et accessibles via l'URL publique Supabase Storage.
-- ══════════════════════════════════════════════════════════════

-- END sql/06_storage.sql

-- ==================================================
-- BEGIN sql/07_migration_campaigns.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- Camply — Migration : Campagnes
-- À exécuter dans l'éditeur SQL de Supabase
-- ══════════════════════════════════════════════════════════════

-- 1. Table principale des campagnes
CREATE TABLE IF NOT EXISTS campaigns (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title            TEXT NOT NULL DEFAULT '',
  description      TEXT NOT NULL DEFAULT '',
  is_public        BOOLEAN NOT NULL DEFAULT FALSE,
  share_code       CHAR(8),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index pour les lookups fréquents
CREATE INDEX IF NOT EXISTS campaigns_user_id_idx    ON campaigns(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS campaigns_share_code_idx ON campaigns(share_code) WHERE share_code IS NOT NULL;

-- 2. Items d'une campagne (références aux entités par share_code)
CREATE TABLE IF NOT EXISTS campaign_items (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_id   UUID NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  item_type     TEXT NOT NULL CHECK (item_type IN ('char', 'chr', 'doc')),
  share_code    CHAR(8) NOT NULL,
  added_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(campaign_id, item_type, share_code)
);

CREATE INDEX IF NOT EXISTS campaign_items_campaign_id_idx ON campaign_items(campaign_id);

-- 3. Abonnements joueurs aux campagnes
CREATE TABLE IF NOT EXISTS followed_campaigns (
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  campaign_id  UUID NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  followed_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, campaign_id)
);

CREATE INDEX IF NOT EXISTS followed_campaigns_user_id_idx ON followed_campaigns(user_id);

-- 4. Génération automatique du share_code à l'insertion/update is_public
CREATE OR REPLACE FUNCTION generate_campaign_share_code()
RETURNS TRIGGER AS $$
DECLARE
  new_code CHAR(8);
  attempts INT := 0;
BEGIN
  -- Génère un code seulement si is_public passe à TRUE et qu'il n'y en a pas encore
  IF NEW.is_public = TRUE AND (OLD.share_code IS NULL OR OLD.is_public = FALSE) THEN
    LOOP
      new_code := upper(substring(md5(random()::text) from 1 for 8));
      EXIT WHEN NOT EXISTS (SELECT 1 FROM campaigns WHERE share_code = new_code);
      attempts := attempts + 1;
      IF attempts > 100 THEN RAISE EXCEPTION 'Could not generate unique share_code'; END IF;
    END LOOP;
    NEW.share_code := new_code;
  END IF;
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS campaigns_share_code_trigger ON campaigns;
CREATE TRIGGER campaigns_share_code_trigger
  BEFORE INSERT OR UPDATE ON campaigns
  FOR EACH ROW EXECUTE FUNCTION generate_campaign_share_code();

-- 5. RLS (Row Level Security)
ALTER TABLE campaigns         ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_items    ENABLE ROW LEVEL SECURITY;
ALTER TABLE followed_campaigns ENABLE ROW LEVEL SECURITY;

-- campaigns : le propriétaire voit tout, les autres voient seulement les publiques
DROP POLICY IF EXISTS campaigns_owner   ON campaigns;
DROP POLICY IF EXISTS campaigns_public  ON campaigns;
CREATE POLICY campaigns_owner  ON campaigns FOR ALL    USING (user_id = auth.uid());
CREATE POLICY campaigns_public ON campaigns FOR SELECT USING (is_public = TRUE);

-- campaign_items : lecture si propriétaire OU si la campagne est publique
DROP POLICY IF EXISTS campaign_items_owner  ON campaign_items;
DROP POLICY IF EXISTS campaign_items_public ON campaign_items;
CREATE POLICY campaign_items_owner  ON campaign_items FOR ALL
  USING (EXISTS (SELECT 1 FROM campaigns WHERE id = campaign_id AND user_id = auth.uid()));
CREATE POLICY campaign_items_public ON campaign_items FOR SELECT
  USING (EXISTS (SELECT 1 FROM campaigns WHERE id = campaign_id AND is_public = TRUE));

-- followed_campaigns : chaque joueur gère ses propres abonnements
DROP POLICY IF EXISTS followed_campaigns_self ON followed_campaigns;
CREATE POLICY followed_campaigns_self ON followed_campaigns FOR ALL
  USING (user_id = auth.uid());

-- END sql/07_migration_campaigns.sql

-- ==================================================
-- BEGIN sql/08_fix-profiles-v2.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- Camply — Correction RLS profils + sync Discord
-- ══════════════════════════════════════════════════════════════

-- ── 1. Corrige les politiques RLS sur profiles ────────────────

DROP POLICY IF EXISTS "profiles_select_own"  ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_own"  ON public.profiles;
DROP POLICY IF EXISTS "profiles_insert_own"  ON public.profiles;
DROP POLICY IF EXISTS "profiles_upsert_own"  ON public.profiles;

-- Lecture : son propre profil uniquement
CREATE POLICY "profiles_select_own" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

-- Lecture publique du username (pour l'affichage dans les partages)
CREATE POLICY "profiles_select_public" ON public.profiles
  FOR SELECT USING (true);

-- Insert : uniquement son propre profil
CREATE POLICY "profiles_insert_own" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

-- Update : uniquement son propre profil
CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);


-- ── 2. Met à jour les profils existants ───────────────────────

UPDATE public.profiles p
SET username = COALESCE(
  u.raw_user_meta_data->>'full_name',
  u.raw_user_meta_data->>'name',
  u.raw_user_meta_data->>'username',
  split_part(u.email, '@', 1)
)
FROM auth.users u
WHERE p.id = u.id;


-- ── 3. Corrige le trigger pour les nouvelles inscriptions ─────

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (
    NEW.id,
    COALESCE(
      NEW.raw_user_meta_data->>'full_name',
      NEW.raw_user_meta_data->>'name',
      NEW.raw_user_meta_data->>'username',
      split_part(NEW.email, '@', 1)
    )
  )
  ON CONFLICT (id) DO UPDATE
    SET username = COALESCE(
      NEW.raw_user_meta_data->>'full_name',
      NEW.raw_user_meta_data->>'name',
      NEW.raw_user_meta_data->>'username',
      split_part(NEW.email, '@', 1)
    );
  RETURN NEW;
END;
$$;

-- ══════════════════════════════════════════════════════════════

-- END sql/08_fix-profiles-v2.sql

-- ==================================================
-- BEGIN sql/09_character_tag.sql
-- ==================================================
-- Table pour les tags locaux sur les personnages suivis
CREATE TABLE IF NOT EXISTS followed_character_tags (
  id           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  character_id uuid NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
  tag_id       uuid NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  created_at   timestamptz DEFAULT now(),
  UNIQUE (user_id, character_id, tag_id)
);

-- Index pour les requêtes fréquentes
CREATE INDEX IF NOT EXISTS idx_followed_character_tags_user
  ON followed_character_tags(user_id);
CREATE INDEX IF NOT EXISTS idx_followed_character_tags_character
  ON followed_character_tags(character_id);

-- RLS
ALTER TABLE followed_character_tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage their own followed tags"
  ON followed_character_tags
  FOR ALL
  USING  (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- END sql/09_character_tag.sql

-- ==================================================
-- BEGIN sql/10_transfer.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- MYSTIC FALLS — Migration : Transfert d'éléments entre joueurs
-- À coller dans : Supabase Dashboard > SQL Editor > New query
-- ══════════════════════════════════════════════════════════════
--
-- Problème RLS : un utilisateur ne peut mettre à jour que ses
-- propres lignes (user_id = auth.uid()). Pour changer le
-- propriétaire d'un objet, il faut contourner le RLS via une
-- fonction SECURITY DEFINER (qui s'exécute avec les droits du
-- propriétaire de la fonction, soit postgres/service_role).
--
-- Sécurité maintenue :
--   1. L'appelant doit être authentifié.
--   2. L'objet doit appartenir à l'appelant (auth.uid()).
--   3. Le destinataire doit exister dans public.profiles.
--   4. On ne peut pas se transférer un objet à soi-même.
-- ══════════════════════════════════════════════════════════════


-- ── Fonction générique de transfert ──────────────────────────

CREATE OR REPLACE FUNCTION public.transfer_item(
  p_item_type   TEXT,   -- 'char' | 'chr' | 'doc' | 'campaign'
  p_share_code  TEXT,   -- code de partage de l'objet
  p_to_username TEXT    -- nom d'utilisateur du destinataire
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER   -- contourne le RLS ; la sécurité est gérée manuellement ci-dessous
SET search_path = public
AS $$
DECLARE
  v_caller_id    UUID := auth.uid();
  v_target_id    UUID;
  v_item_id      UUID;
  v_item_user_id UUID;
BEGIN

  -- 1. L'appelant doit être connecté
  IF v_caller_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated');
  END IF;

  -- 2. Résoudre le destinataire
  SELECT id INTO v_target_id
  FROM public.profiles
  WHERE lower(username) = lower(trim(p_to_username))
  LIMIT 1;

  IF v_target_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'user_not_found');
  END IF;

  -- 3. Pas de transfert vers soi-même
  IF v_target_id = v_caller_id THEN
    RETURN jsonb_build_object('ok', false, 'error', 'same_user');
  END IF;

  -- ── CAS : personnage ────────────────────────────────────────
  IF p_item_type = 'char' THEN

    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.characters
    WHERE share_code = upper(trim(p_share_code))
    LIMIT 1;

    IF v_item_id IS NULL THEN
      RETURN jsonb_build_object('ok', false, 'error', 'item_not_found');
    END IF;
    IF v_item_user_id <> v_caller_id THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_owner');
    END IF;

    -- Nettoyer les tags orphelins AVANT le transfert
    -- (les character_tags appartiennent à l'ancien user via les tags)
    PERFORM public._cleanup_char_tags_on_transfer(v_item_id, v_caller_id);

    -- Supprimer les followed_characters de l'ancien proprio sur cet objet
    DELETE FROM public.followed_characters
    WHERE character_id = v_item_id AND user_id = v_caller_id;

    -- Transférer
    UPDATE public.characters
    SET user_id = v_target_id, updated_at = NOW()
    WHERE id = v_item_id;

  -- ── CAS : chronique ─────────────────────────────────────────
  ELSIF p_item_type = 'chr' THEN

    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.chronicles
    WHERE share_code = upper(trim(p_share_code))
    LIMIT 1;

    IF v_item_id IS NULL THEN
      RETURN jsonb_build_object('ok', false, 'error', 'item_not_found');
    END IF;
    IF v_item_user_id <> v_caller_id THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_owner');
    END IF;

    -- Supprimer l'abonnement éventuel de l'ancien proprio
    DELETE FROM public.followed_chronicles
    WHERE chronicle_id = v_item_id AND user_id = v_caller_id;

    UPDATE public.chronicles
    SET user_id = v_target_id, updated_at = NOW()
    WHERE id = v_item_id;

  -- ── CAS : document ──────────────────────────────────────────
  ELSIF p_item_type = 'doc' THEN

    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.documents
    WHERE share_code = upper(trim(p_share_code))
    LIMIT 1;

    IF v_item_id IS NULL THEN
      RETURN jsonb_build_object('ok', false, 'error', 'item_not_found');
    END IF;
    IF v_item_user_id <> v_caller_id THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_owner');
    END IF;

    -- Nettoyer les doc_tags orphelins
    PERFORM public._cleanup_doc_tags_on_transfer(v_item_id, v_caller_id);

    DELETE FROM public.followed_documents
    WHERE document_id = v_item_id AND user_id = v_caller_id;

    UPDATE public.documents
    SET user_id = v_target_id, updated_at = NOW()
    WHERE id = v_item_id;

  -- ── CAS : campagne ──────────────────────────────────────────
  ELSIF p_item_type = 'campaign' THEN

    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.campaigns
    WHERE share_code = upper(trim(p_share_code))
    LIMIT 1;

    IF v_item_id IS NULL THEN
      RETURN jsonb_build_object('ok', false, 'error', 'item_not_found');
    END IF;
    IF v_item_user_id <> v_caller_id THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_owner');
    END IF;

    DELETE FROM public.followed_campaigns
    WHERE campaign_id = v_item_id AND user_id = v_caller_id;

    UPDATE public.campaigns
    SET user_id = v_target_id, updated_at = NOW()
    WHERE id = v_item_id;

  ELSE
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_type');
  END IF;

  RETURN jsonb_build_object('ok', true, 'item_id', v_item_id, 'to_user_id', v_target_id);
END;
$$;

-- Autoriser les utilisateurs connectés à appeler cette fonction
GRANT EXECUTE ON FUNCTION public.transfer_item(TEXT, TEXT, TEXT) TO authenticated;


-- ── Helper : nettoyage des tags personnage avant transfert ────
-- Supprime les liaisons character_tags de cet item pour l'ancien
-- propriétaire, puis supprime les tags devenu orphelins.

CREATE OR REPLACE FUNCTION public._cleanup_char_tags_on_transfer(
  p_char_id UUID,
  p_user_id UUID
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tag_id UUID;
  v_count  INT;
BEGIN
  -- Pour chaque tag lié au personnage transféré
  FOR v_tag_id IN
    SELECT tag_id FROM public.character_tags WHERE character_id = p_char_id
  LOOP
    -- Vérifie si ce tag est encore utilisé ailleurs par cet utilisateur
    SELECT COUNT(*) INTO v_count
    FROM public.character_tags ct
    JOIN public.characters c ON c.id = ct.character_id
    WHERE ct.tag_id = v_tag_id
      AND c.user_id = p_user_id
      AND c.id <> p_char_id;

    -- Aussi dans les followed_character_tags
    IF v_count = 0 THEN
      SELECT COUNT(*) INTO v_count
      FROM public.followed_character_tags
      WHERE tag_id = v_tag_id AND user_id = p_user_id;
    END IF;

    -- Tag orphelin → on le supprime
    IF v_count = 0 THEN
      DELETE FROM public.tags WHERE id = v_tag_id AND user_id = p_user_id;
    END IF;
  END LOOP;

  -- Supprime les liaisons character_tags pour ce personnage
  DELETE FROM public.character_tags WHERE character_id = p_char_id;

  -- Supprime aussi les followed_character_tags locaux d'autres users
  DELETE FROM public.followed_character_tags WHERE character_id = p_char_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public._cleanup_char_tags_on_transfer(UUID, UUID) TO authenticated;


-- ── Helper : nettoyage des tags document avant transfert ──────

CREATE OR REPLACE FUNCTION public._cleanup_doc_tags_on_transfer(
  p_doc_id  UUID,
  p_user_id UUID
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tag_id UUID;
  v_count  INT;
BEGIN
  FOR v_tag_id IN
    SELECT tag_id FROM public.document_tags WHERE document_id = p_doc_id
  LOOP
    SELECT COUNT(*) INTO v_count
    FROM public.document_tags dt
    JOIN public.documents d ON d.id = dt.document_id
    WHERE dt.tag_id = v_tag_id
      AND d.user_id = p_user_id
      AND d.id <> p_doc_id;

    IF v_count = 0 THEN
      SELECT COUNT(*) INTO v_count
      FROM public.followed_document_tags
      WHERE tag_id = v_tag_id AND user_id = p_user_id;
    END IF;

    IF v_count = 0 THEN
      DELETE FROM public.doc_tags WHERE id = v_tag_id AND user_id = p_user_id;
    END IF;
  END LOOP;

  DELETE FROM public.document_tags WHERE document_id = p_doc_id;
  DELETE FROM public.followed_document_tags WHERE document_id = p_doc_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public._cleanup_doc_tags_on_transfer(UUID, UUID) TO authenticated;


-- ══════════════════════════════════════════════════════════════
-- Résumé de ce que fait ce fichier :
--
--  • transfer_item(type, share_code, username)
--      RPC appelable depuis le client JS via sb.rpc().
--      Vérifie que l'appelant est bien le propriétaire, résout
--      le destinataire par username, nettoie les tags orphelins,
--      puis change le user_id de la ligne concernée.
--
--  • _cleanup_char_tags_on_transfer / _cleanup_doc_tags_on_transfer
--      Fonctions internes appelées par transfer_item.
--      Suppriment les liaisons tags de l'objet transféré et
--      purgent les tags devenus orphelins pour l'ancien proprio.
--
-- Sécurité : SECURITY DEFINER + vérification explicite de
-- auth.uid() = v_item_user_id avant tout UPDATE.
-- ══════════════════════════════════════════════════════════════

-- END sql/10_transfer.sql

-- ==================================================
-- BEGIN sql/11_transfer_auto_follow.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- Camply — Patch : abonnement automatique après transfert
-- Après un transfert, l'ancien propriétaire est automatiquement
-- abonné à l'objet qu'il vient de céder.
-- À coller dans : Supabase Dashboard > SQL Editor > New query
-- ══════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.transfer_item(
  p_item_type   TEXT,   -- 'char' | 'chr' | 'doc' | 'campaign'
  p_share_code  TEXT,   -- code de partage de l'objet
  p_to_username TEXT    -- nom d'utilisateur du destinataire
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller_id    UUID := auth.uid();
  v_target_id    UUID;
  v_item_id      UUID;
  v_item_user_id UUID;
BEGIN

  -- 1. L'appelant doit être connecté
  IF v_caller_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated');
  END IF;

  -- 2. Résoudre le destinataire
  SELECT id INTO v_target_id
  FROM public.profiles
  WHERE lower(username) = lower(trim(p_to_username))
  LIMIT 1;

  IF v_target_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'user_not_found');
  END IF;

  -- 3. Pas de transfert vers soi-même
  IF v_target_id = v_caller_id THEN
    RETURN jsonb_build_object('ok', false, 'error', 'same_user');
  END IF;

  -- ── CAS : personnage ────────────────────────────────────────
  IF p_item_type = 'char' THEN

    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.characters
    WHERE share_code = upper(trim(p_share_code))
    LIMIT 1;

    IF v_item_id IS NULL THEN
      RETURN jsonb_build_object('ok', false, 'error', 'item_not_found');
    END IF;
    IF v_item_user_id <> v_caller_id THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_owner');
    END IF;

    -- Nettoyer les tags orphelins AVANT le transfert
    PERFORM public._cleanup_char_tags_on_transfer(v_item_id, v_caller_id);

    -- Supprimer l'abonnement éventuel de l'ancien proprio (évite le doublon)
    DELETE FROM public.followed_characters
    WHERE character_id = v_item_id AND user_id = v_caller_id;

    -- Transférer
    UPDATE public.characters
    SET user_id = v_target_id, updated_at = NOW()
    WHERE id = v_item_id;

    -- Abonner automatiquement l'ancien propriétaire
    -- (l'objet est maintenant public sinon il ne pouvait pas être transféré)
    INSERT INTO public.followed_characters (user_id, character_id)
    VALUES (v_caller_id, v_item_id)
    ON CONFLICT DO NOTHING;

  -- ── CAS : chronique ─────────────────────────────────────────
  ELSIF p_item_type = 'chr' THEN

    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.chronicles
    WHERE share_code = upper(trim(p_share_code))
    LIMIT 1;

    IF v_item_id IS NULL THEN
      RETURN jsonb_build_object('ok', false, 'error', 'item_not_found');
    END IF;
    IF v_item_user_id <> v_caller_id THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_owner');
    END IF;

    -- Supprimer l'abonnement éventuel de l'ancien proprio (évite le doublon)
    DELETE FROM public.followed_chronicles
    WHERE chronicle_id = v_item_id AND user_id = v_caller_id;

    -- Transférer
    UPDATE public.chronicles
    SET user_id = v_target_id, updated_at = NOW()
    WHERE id = v_item_id;

    -- Abonner automatiquement l'ancien propriétaire
    INSERT INTO public.followed_chronicles (user_id, chronicle_id)
    VALUES (v_caller_id, v_item_id)
    ON CONFLICT DO NOTHING;

  -- ── CAS : document ──────────────────────────────────────────
  ELSIF p_item_type = 'doc' THEN

    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.documents
    WHERE share_code = upper(trim(p_share_code))
    LIMIT 1;

    IF v_item_id IS NULL THEN
      RETURN jsonb_build_object('ok', false, 'error', 'item_not_found');
    END IF;
    IF v_item_user_id <> v_caller_id THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_owner');
    END IF;

    -- Nettoyer les doc_tags orphelins
    PERFORM public._cleanup_doc_tags_on_transfer(v_item_id, v_caller_id);

    -- Supprimer l'abonnement éventuel de l'ancien proprio (évite le doublon)
    DELETE FROM public.followed_documents
    WHERE document_id = v_item_id AND user_id = v_caller_id;

    -- Transférer
    UPDATE public.documents
    SET user_id = v_target_id, updated_at = NOW()
    WHERE id = v_item_id;

    -- Abonner automatiquement l'ancien propriétaire
    INSERT INTO public.followed_documents (user_id, document_id)
    VALUES (v_caller_id, v_item_id)
    ON CONFLICT DO NOTHING;

  -- ── CAS : campagne ──────────────────────────────────────────
  ELSIF p_item_type = 'campaign' THEN

    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.campaigns
    WHERE share_code = upper(trim(p_share_code))
    LIMIT 1;

    IF v_item_id IS NULL THEN
      RETURN jsonb_build_object('ok', false, 'error', 'item_not_found');
    END IF;
    IF v_item_user_id <> v_caller_id THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_owner');
    END IF;

    -- Supprimer l'abonnement éventuel de l'ancien proprio (évite le doublon)
    DELETE FROM public.followed_campaigns
    WHERE campaign_id = v_item_id AND user_id = v_caller_id;

    -- Transférer
    UPDATE public.campaigns
    SET user_id = v_target_id, updated_at = NOW()
    WHERE id = v_item_id;

    -- Abonner automatiquement l'ancien propriétaire
    INSERT INTO public.followed_campaigns (user_id, campaign_id)
    VALUES (v_caller_id, v_item_id)
    ON CONFLICT DO NOTHING;

  ELSE
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_type');
  END IF;

  RETURN jsonb_build_object('ok', true, 'item_id', v_item_id, 'to_user_id', v_target_id);
END;
$$;

-- Les GRANT existants sont conservés
GRANT EXECUTE ON FUNCTION public.transfer_item(TEXT, TEXT, TEXT) TO authenticated;

-- END sql/11_transfer_auto_follow.sql

-- ==================================================
-- BEGIN sql/12_transfer_fix_double.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- Camply — Patch v2 : transfert + nettoyage abonnement
-- destinataire + abonnement automatique ancien proprio
-- À coller dans : Supabase Dashboard > SQL Editor > New query
-- ══════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.transfer_item(
  p_item_type   TEXT,
  p_share_code  TEXT,
  p_to_username TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller_id    UUID := auth.uid();
  v_target_id    UUID;
  v_item_id      UUID;
  v_item_user_id UUID;
BEGIN

  -- 1. L'appelant doit être connecté
  IF v_caller_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated');
  END IF;

  -- 2. Résoudre le destinataire
  SELECT id INTO v_target_id
  FROM public.profiles
  WHERE lower(username) = lower(trim(p_to_username))
  LIMIT 1;

  IF v_target_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'user_not_found');
  END IF;

  -- 3. Pas de transfert vers soi-même
  IF v_target_id = v_caller_id THEN
    RETURN jsonb_build_object('ok', false, 'error', 'same_user');
  END IF;

  -- ── CAS : personnage ────────────────────────────────────────
  IF p_item_type = 'char' THEN

    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.characters
    WHERE share_code = upper(trim(p_share_code))
    LIMIT 1;

    IF v_item_id IS NULL THEN
      RETURN jsonb_build_object('ok', false, 'error', 'item_not_found');
    END IF;
    IF v_item_user_id <> v_caller_id THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_owner');
    END IF;

    PERFORM public._cleanup_char_tags_on_transfer(v_item_id, v_caller_id);

    -- Supprime l'abonnement de l'ancien proprio (évite le doublon côté followedChars)
    DELETE FROM public.followed_characters
    WHERE character_id = v_item_id AND user_id = v_caller_id;

    -- Supprime l'abonnement du destinataire s'il en avait un
    -- (il va devenir propriétaire, inutile d'être aussi abonné)
    DELETE FROM public.followed_characters
    WHERE character_id = v_item_id AND user_id = v_target_id;

    UPDATE public.characters
    SET user_id = v_target_id, updated_at = NOW()
    WHERE id = v_item_id;

    -- Abonne automatiquement l'ancien propriétaire
    INSERT INTO public.followed_characters (user_id, character_id)
    VALUES (v_caller_id, v_item_id)
    ON CONFLICT DO NOTHING;

  -- ── CAS : chronique ─────────────────────────────────────────
  ELSIF p_item_type = 'chr' THEN

    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.chronicles
    WHERE share_code = upper(trim(p_share_code))
    LIMIT 1;

    IF v_item_id IS NULL THEN
      RETURN jsonb_build_object('ok', false, 'error', 'item_not_found');
    END IF;
    IF v_item_user_id <> v_caller_id THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_owner');
    END IF;

    DELETE FROM public.followed_chronicles
    WHERE chronicle_id = v_item_id AND user_id = v_caller_id;

    DELETE FROM public.followed_chronicles
    WHERE chronicle_id = v_item_id AND user_id = v_target_id;

    UPDATE public.chronicles
    SET user_id = v_target_id, updated_at = NOW()
    WHERE id = v_item_id;

    INSERT INTO public.followed_chronicles (user_id, chronicle_id)
    VALUES (v_caller_id, v_item_id)
    ON CONFLICT DO NOTHING;

  -- ── CAS : document ──────────────────────────────────────────
  ELSIF p_item_type = 'doc' THEN

    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.documents
    WHERE share_code = upper(trim(p_share_code))
    LIMIT 1;

    IF v_item_id IS NULL THEN
      RETURN jsonb_build_object('ok', false, 'error', 'item_not_found');
    END IF;
    IF v_item_user_id <> v_caller_id THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_owner');
    END IF;

    PERFORM public._cleanup_doc_tags_on_transfer(v_item_id, v_caller_id);

    DELETE FROM public.followed_documents
    WHERE document_id = v_item_id AND user_id = v_caller_id;

    DELETE FROM public.followed_documents
    WHERE document_id = v_item_id AND user_id = v_target_id;

    UPDATE public.documents
    SET user_id = v_target_id, updated_at = NOW()
    WHERE id = v_item_id;

    INSERT INTO public.followed_documents (user_id, document_id)
    VALUES (v_caller_id, v_item_id)
    ON CONFLICT DO NOTHING;

  -- ── CAS : campagne ──────────────────────────────────────────
  ELSIF p_item_type = 'campaign' THEN

    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.campaigns
    WHERE share_code = upper(trim(p_share_code))
    LIMIT 1;

    IF v_item_id IS NULL THEN
      RETURN jsonb_build_object('ok', false, 'error', 'item_not_found');
    END IF;
    IF v_item_user_id <> v_caller_id THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_owner');
    END IF;

    DELETE FROM public.followed_campaigns
    WHERE campaign_id = v_item_id AND user_id = v_caller_id;

    DELETE FROM public.followed_campaigns
    WHERE campaign_id = v_item_id AND user_id = v_target_id;

    UPDATE public.campaigns
    SET user_id = v_target_id, updated_at = NOW()
    WHERE id = v_item_id;

    INSERT INTO public.followed_campaigns (user_id, campaign_id)
    VALUES (v_caller_id, v_item_id)
    ON CONFLICT DO NOTHING;

  ELSE
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_type');
  END IF;

  RETURN jsonb_build_object('ok', true, 'item_id', v_item_id, 'to_user_id', v_target_id);
END;
$$;

GRANT EXECUTE ON FUNCTION public.transfer_item(TEXT, TEXT, TEXT) TO authenticated;

-- END sql/12_transfer_fix_double.sql

-- ==================================================
-- BEGIN sql/13_sync_owner_tags.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- Camply — Patch : sync tags propriétaire → abonnés (v2)
-- Corrections :
--   1. Signature RPC compatible PostgREST (p_item_id en TEXT
--      pour éviter les erreurs de cast depuis le JS, converti
--      en UUID en interne)
--   2. Fonction cleanup_follower_tags : supprime les tags
--      devenus orphelins quand un abonné se désabonne ou
--      retire un tag local
-- ══════════════════════════════════════════════════════════════

-- ── 1. sync_char_tags_to_follower ─────────────────────────────

CREATE OR REPLACE FUNCTION public.sync_char_tags_to_follower(
  p_character_id UUID,
  p_follower_id  UUID
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  r            RECORD;
  v_new_tag_id UUID;
BEGIN
  FOR r IN
    SELECT t.name, t.color
    FROM   public.character_tags ct
    JOIN   public.tags t ON t.id = ct.tag_id
    WHERE  ct.character_id = p_character_id
  LOOP
    -- Cherche un tag du même nom chez l'abonné
    SELECT id INTO v_new_tag_id
    FROM   public.tags
    WHERE  user_id = p_follower_id
      AND  lower(name) = lower(r.name)
    LIMIT 1;

    -- Crée-le si absent
    IF v_new_tag_id IS NULL THEN
      INSERT INTO public.tags (user_id, name, color)
      VALUES (p_follower_id, r.name, r.color)
      ON CONFLICT (user_id, name) DO NOTHING
      RETURNING id INTO v_new_tag_id;

      IF v_new_tag_id IS NULL THEN
        SELECT id INTO v_new_tag_id
        FROM   public.tags
        WHERE  user_id = p_follower_id AND lower(name) = lower(r.name)
        LIMIT 1;
      END IF;
    END IF;

    IF v_new_tag_id IS NOT NULL THEN
      INSERT INTO public.followed_character_tags (user_id, character_id, tag_id)
      VALUES (p_follower_id, p_character_id, v_new_tag_id)
      ON CONFLICT DO NOTHING;
    END IF;
  END LOOP;
END;
$$;

GRANT EXECUTE ON FUNCTION public.sync_char_tags_to_follower(UUID, UUID) TO authenticated;


-- ── 2. sync_doc_tags_to_follower ──────────────────────────────

CREATE OR REPLACE FUNCTION public.sync_doc_tags_to_follower(
  p_document_id UUID,
  p_follower_id UUID
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  r            RECORD;
  v_new_tag_id UUID;
BEGIN
  FOR r IN
    SELECT t.name, t.color
    FROM   public.document_tags dt
    JOIN   public.doc_tags t ON t.id = dt.tag_id
    WHERE  dt.document_id = p_document_id
  LOOP
    SELECT id INTO v_new_tag_id
    FROM   public.doc_tags
    WHERE  user_id = p_follower_id
      AND  lower(name) = lower(r.name)
    LIMIT 1;

    IF v_new_tag_id IS NULL THEN
      INSERT INTO public.doc_tags (user_id, name, color)
      VALUES (p_follower_id, r.name, r.color)
      ON CONFLICT (user_id, name) DO NOTHING
      RETURNING id INTO v_new_tag_id;

      IF v_new_tag_id IS NULL THEN
        SELECT id INTO v_new_tag_id
        FROM   public.doc_tags
        WHERE  user_id = p_follower_id AND lower(name) = lower(r.name)
        LIMIT 1;
      END IF;
    END IF;

    IF v_new_tag_id IS NOT NULL THEN
      INSERT INTO public.followed_document_tags (user_id, document_id, tag_id)
      VALUES (p_follower_id, p_document_id, v_new_tag_id)
      ON CONFLICT DO NOTHING;
    END IF;
  END LOOP;
END;
$$;

GRANT EXECUTE ON FUNCTION public.sync_doc_tags_to_follower(UUID, UUID) TO authenticated;


-- ── 3. sync_owner_tags — RPC principale ───────────────────────
-- p_item_id est déclaré en TEXT pour éviter les erreurs de cast
-- PostgREST quand le JS envoie une chaîne UUID.

DROP FUNCTION IF EXISTS public.sync_owner_tags(TEXT, UUID);
DROP FUNCTION IF EXISTS public.sync_owner_tags(TEXT, TEXT);

CREATE OR REPLACE FUNCTION public.sync_owner_tags(
  p_item_type TEXT,
  p_item_id   TEXT   -- reçu comme TEXT depuis PostgREST, converti en UUID en interne
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller_id UUID := auth.uid();
  v_uuid      UUID;
BEGIN
  IF v_caller_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated');
  END IF;

  -- Cast sécurisé TEXT → UUID
  BEGIN
    v_uuid := p_item_id::UUID;
  EXCEPTION WHEN invalid_text_representation THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_uuid');
  END;

  IF p_item_type = 'char' THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.followed_characters
      WHERE  user_id = v_caller_id AND character_id = v_uuid
    ) AND NOT EXISTS (
      SELECT 1 FROM public.characters
      WHERE  id = v_uuid AND user_id = v_caller_id
    ) THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_follower');
    END IF;
    PERFORM public.sync_char_tags_to_follower(v_uuid, v_caller_id);

  ELSIF p_item_type = 'doc' THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.followed_documents
      WHERE  user_id = v_caller_id AND document_id = v_uuid
    ) AND NOT EXISTS (
      SELECT 1 FROM public.documents
      WHERE  id = v_uuid AND user_id = v_caller_id
    ) THEN
      RETURN jsonb_build_object('ok', false, 'error', 'not_follower');
    END IF;
    PERFORM public.sync_doc_tags_to_follower(v_uuid, v_caller_id);

  ELSE
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_type');
  END IF;

  RETURN jsonb_build_object('ok', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.sync_owner_tags(TEXT, TEXT) TO authenticated;


-- ── 4. cleanup_orphan_char_tags ───────────────────────────────
-- Supprime les tags de l'abonné (table `tags`) qui ne sont plus
-- utilisés nulle part après un désabonnement ou un retrait de tag.
-- Appelée depuis le JS après unfollowChar() ou removeFollowedTag().

CREATE OR REPLACE FUNCTION public.cleanup_orphan_char_tags(
  p_user_id UUID
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tag_id UUID;
BEGIN
  FOR v_tag_id IN
    -- Tags de cet utilisateur qui ne sont plus liés à rien
    SELECT t.id
    FROM   public.tags t
    WHERE  t.user_id = p_user_id
      AND  NOT EXISTS (
             SELECT 1 FROM public.character_tags ct WHERE ct.tag_id = t.id
           )
      AND  NOT EXISTS (
             SELECT 1 FROM public.followed_character_tags fct
             WHERE  fct.tag_id = t.id AND fct.user_id = p_user_id
           )
  LOOP
    DELETE FROM public.tags WHERE id = v_tag_id AND user_id = p_user_id;
  END LOOP;
END;
$$;

GRANT EXECUTE ON FUNCTION public.cleanup_orphan_char_tags(UUID) TO authenticated;


-- ── 5. cleanup_orphan_doc_tags ────────────────────────────────

CREATE OR REPLACE FUNCTION public.cleanup_orphan_doc_tags(
  p_user_id UUID
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tag_id UUID;
BEGIN
  FOR v_tag_id IN
    SELECT t.id
    FROM   public.doc_tags t
    WHERE  t.user_id = p_user_id
      AND  NOT EXISTS (
             SELECT 1 FROM public.document_tags dt WHERE dt.tag_id = t.id
           )
      AND  NOT EXISTS (
             SELECT 1 FROM public.followed_document_tags fdt
             WHERE  fdt.tag_id = t.id AND fdt.user_id = p_user_id
           )
  LOOP
    DELETE FROM public.doc_tags WHERE id = v_tag_id AND user_id = p_user_id;
  END LOOP;
END;
$$;

GRANT EXECUTE ON FUNCTION public.cleanup_orphan_doc_tags(UUID) TO authenticated;

-- END sql/13_sync_owner_tags.sql

-- ==================================================
-- BEGIN sql/14_fix_doc_tags_unique_conflict.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- Fix: sync_owner_tags RPC fails on ON CONFLICT(user_id, name)
-- because doc_tags had no matching unique constraint.
--
-- This migration:
--   1) Deduplicates doc_tags by (user_id, name)
--   2) Re-points links in document_tags / followed_document_tags
--   3) Adds the missing UNIQUE (user_id, name) constraint
-- ══════════════════════════════════════════════════════════════

BEGIN;

-- Ensure any duplicate links created while remapping do not fail
CREATE TEMP TABLE _doc_tags_dedup AS
SELECT
  id,
  user_id,
  name,
  ROW_NUMBER() OVER (
    PARTITION BY user_id, name
    ORDER BY created_at NULLS LAST, id
  ) AS rn,
  FIRST_VALUE(id) OVER (
    PARTITION BY user_id, name
    ORDER BY created_at NULLS LAST, id
  ) AS keep_id
FROM public.doc_tags;

-- Repoint owner document tag links to the kept tag id
UPDATE public.document_tags dt
SET tag_id = d.keep_id
FROM _doc_tags_dedup d
WHERE dt.tag_id = d.id
  AND d.rn > 1
  AND dt.tag_id <> d.keep_id
  AND NOT EXISTS (
    SELECT 1
    FROM public.document_tags dt2
    WHERE dt2.document_id = dt.document_id
      AND dt2.tag_id = d.keep_id
  );

-- Remove duplicates now made redundant by the remap
DELETE FROM public.document_tags dt
USING _doc_tags_dedup d
WHERE dt.tag_id = d.id
  AND d.rn > 1;

-- Repoint followed document tag links to the kept tag id
UPDATE public.followed_document_tags fdt
SET tag_id = d.keep_id
FROM _doc_tags_dedup d
WHERE fdt.tag_id = d.id
  AND d.rn > 1
  AND fdt.tag_id <> d.keep_id
  AND NOT EXISTS (
    SELECT 1
    FROM public.followed_document_tags fdt2
    WHERE fdt2.user_id = fdt.user_id
      AND fdt2.document_id = fdt.document_id
      AND fdt2.tag_id = d.keep_id
  );

-- Remove duplicates now made redundant by the remap
DELETE FROM public.followed_document_tags fdt
USING _doc_tags_dedup d
WHERE fdt.tag_id = d.id
  AND d.rn > 1;

-- Delete duplicate tag rows, keeping one per (user_id, name)
DELETE FROM public.doc_tags t
USING _doc_tags_dedup d
WHERE t.id = d.id
  AND d.rn > 1;

-- Add missing uniqueness required by ON CONFLICT (user_id, name)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'doc_tags_user_id_name_key'
      AND conrelid = 'public.doc_tags'::regclass
  ) THEN
    ALTER TABLE public.doc_tags
      ADD CONSTRAINT doc_tags_user_id_name_key UNIQUE (user_id, name);
  END IF;
END $$;

COMMIT;

-- END sql/14_fix_doc_tags_unique_conflict.sql

-- ==================================================
-- BEGIN sql/15_map_markers.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- CAMPLY — Marqueurs de carte personnels
-- À coller dans : Supabase Dashboard > SQL Editor > New query
-- ══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.map_markers (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Position exprimée en pourcentage de l'image (0.0 → 1.0)
  -- Indépendant de la résolution affichée.
  x           DOUBLE PRECISION NOT NULL CHECK (x >= 0 AND x <= 1),
  y           DOUBLE PRECISION NOT NULL CHECK (y >= 0 AND y <= 1),

  name        TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  color       TEXT NOT NULL DEFAULT '#e8c46a',

  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Index pour récupérer rapidement les marqueurs d'un utilisateur
CREATE INDEX IF NOT EXISTS map_markers_user_id_idx ON public.map_markers(user_id);

-- Trigger updated_at (réutilise la fonction créée dans 00_schema.sql)
DROP TRIGGER IF EXISTS on_map_markers_updated ON public.map_markers;
CREATE TRIGGER on_map_markers_updated
  BEFORE UPDATE ON public.map_markers
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- ── RLS ──────────────────────────────────────────────────────
ALTER TABLE public.map_markers ENABLE ROW LEVEL SECURITY;

-- Chaque utilisateur gère uniquement ses propres marqueurs
DROP POLICY IF EXISTS "map_markers_all_own" ON public.map_markers;
CREATE POLICY "map_markers_all_own"
  ON public.map_markers
  FOR ALL
  USING  (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ══════════════════════════════════════════════════════════════
-- Les marqueurs sont stockés avec une position relative (0→1)
-- afin d'être indépendants des dimensions d'affichage.
-- ══════════════════════════════════════════════════════════════

-- END sql/15_map_markers.sql

-- ==================================================
-- BEGIN sql/16_map_sharing.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- CAMPLY — Partage des marqueurs de carte (map_layers)
-- Migration à appliquer APRÈS 15_map_markers.sql
-- ══════════════════════════════════════════════════════════════
--
-- Modèle choisi :
--   Chaque utilisateur possède UNE couche de marqueurs (map_layer).
--   Il peut la rendre publique via un share_code.
--   Les autres joueurs s'y abonnent et voient les marqueurs
--   en lecture seule superposés à leur propre carte.
--   Une couche peut être incluse dans une campagne (type 'map').
-- ══════════════════════════════════════════════════════════════


-- ── 1. Ajouter share_code + is_public sur map_markers ─────────
-- On ajoute les colonnes de partage directement sur la table
-- existante plutôt que de créer une table intermédiaire,
-- car chaque marqueur appartient à un utilisateur identifié
-- et les abonnés voient TOUS les marqueurs d'un propriétaire.

ALTER TABLE public.map_markers
  ADD COLUMN IF NOT EXISTS is_public  BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS share_code TEXT    UNIQUE;

-- Index pour la recherche par code
CREATE INDEX IF NOT EXISTS map_markers_share_code_idx
  ON public.map_markers(share_code) WHERE share_code IS NOT NULL;


-- ── 2. Table map_layers ───────────────────────────────────────
-- Représente la "couche de marqueurs" partageable d'un utilisateur.
-- Un utilisateur n'en possède qu'une (UNIQUE user_id).
-- Elle regroupe tous ses marqueurs publics sous un seul code.

CREATE TABLE IF NOT EXISTS public.map_layers (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title       TEXT NOT NULL DEFAULT '',        -- ex: "Carte de Théodric"
  description TEXT NOT NULL DEFAULT '',
  is_public   BOOLEAN NOT NULL DEFAULT FALSE,
  share_code  TEXT UNIQUE,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id)   -- une seule couche par utilisateur
);

CREATE INDEX IF NOT EXISTS map_layers_user_id_idx   ON public.map_layers(user_id);
CREATE INDEX IF NOT EXISTS map_layers_public_idx    ON public.map_layers(is_public) WHERE is_public = TRUE;

-- Trigger updated_at
DROP TRIGGER IF EXISTS on_map_layers_updated ON public.map_layers;
CREATE TRIGGER on_map_layers_updated
  BEFORE UPDATE ON public.map_layers
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- Génération automatique du share_code lors du passage en public
DROP TRIGGER IF EXISTS set_map_layer_share_code ON public.map_layers;
CREATE TRIGGER set_map_layer_share_code
  BEFORE INSERT ON public.map_layers
  FOR EACH ROW
  WHEN (NEW.share_code IS NULL)
  EXECUTE FUNCTION public.generate_share_code();


-- ── 3. Table followed_map_layers ──────────────────────────────

CREATE TABLE IF NOT EXISTS public.followed_map_layers (
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  layer_id     UUID NOT NULL REFERENCES public.map_layers(id) ON DELETE CASCADE,
  followed_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY  (user_id, layer_id)
);

CREATE INDEX IF NOT EXISTS followed_map_layers_user_idx ON public.followed_map_layers(user_id);


-- ── 4. RLS ────────────────────────────────────────────────────

ALTER TABLE public.map_layers          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.followed_map_layers ENABLE ROW LEVEL SECURITY;

-- map_layers : propriétaire voit tout ; autres voient les publiques
DROP POLICY IF EXISTS "map_layers_select"      ON public.map_layers;
DROP POLICY IF EXISTS "map_layers_select_anon" ON public.map_layers;
DROP POLICY IF EXISTS "map_layers_insert"      ON public.map_layers;
DROP POLICY IF EXISTS "map_layers_update"      ON public.map_layers;
DROP POLICY IF EXISTS "map_layers_delete"      ON public.map_layers;

CREATE POLICY "map_layers_select" ON public.map_layers FOR SELECT
  USING (auth.uid() = user_id OR is_public = TRUE);

CREATE POLICY "map_layers_select_anon" ON public.map_layers FOR SELECT
  TO anon USING (is_public = TRUE);

CREATE POLICY "map_layers_insert" ON public.map_layers FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "map_layers_update" ON public.map_layers FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "map_layers_delete" ON public.map_layers FOR DELETE
  USING (auth.uid() = user_id);

-- followed_map_layers : chaque joueur gère ses propres abonnements
DROP POLICY IF EXISTS "followed_map_layers_all" ON public.followed_map_layers;
CREATE POLICY "followed_map_layers_all" ON public.followed_map_layers FOR ALL
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- ── 5. RLS sur map_markers : exposer les marqueurs publics ────
-- Les marqueurs d'une couche publique sont lisibles par tous
-- (authentifiés ou non) dès lors que la couche est publique.

DROP POLICY IF EXISTS "map_markers_all_own"        ON public.map_markers;
DROP POLICY IF EXISTS "map_markers_select_followed" ON public.map_markers;
DROP POLICY IF EXISTS "map_markers_select_anon"     ON public.map_markers;

-- Propriétaire : lecture + écriture complète
CREATE POLICY "map_markers_all_own" ON public.map_markers FOR ALL
  USING  (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Abonnés authentifiés : lecture des marqueurs des couches publiques suivies
CREATE POLICY "map_markers_select_followed" ON public.map_markers FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.map_layers ml
      JOIN   public.followed_map_layers fml ON fml.layer_id = ml.id
      WHERE  ml.user_id   = map_markers.user_id
        AND  ml.is_public = TRUE
        AND  fml.user_id  = auth.uid()
    )
  );

-- Anonymes : lecture des marqueurs appartenant à une couche publique
CREATE POLICY "map_markers_select_anon" ON public.map_markers FOR SELECT
  TO anon
  USING (
    EXISTS (
      SELECT 1 FROM public.map_layers ml
      WHERE  ml.user_id   = map_markers.user_id
        AND  ml.is_public = TRUE
    )
  );


-- ── 6. Intégration campagnes ──────────────────────────────────
-- Le type 'map' est déjà supporté par campaign_items (colonne
-- item_type TEXT CHECK (item_type IN ('char','chr','doc'))).
-- On étend la contrainte pour accepter 'map'.

ALTER TABLE public.campaign_items
  DROP CONSTRAINT IF EXISTS campaign_items_item_type_check;

ALTER TABLE public.campaign_items
  ADD CONSTRAINT campaign_items_item_type_check
  CHECK (item_type IN ('char', 'chr', 'doc', 'map'));


-- ── 7. Intégration transfer_item ──────────────────────────────
-- Le transfert d'une couche de carte suit le même mécanisme
-- que pour les autres types. La fonction transfer_item sera
-- mise à jour côté JS (map.js) — aucune modification SQL
-- n'est nécessaire car map_layers a déjà user_id + share_code.

-- Pour que transfer_item puisse UPDATE map_layers, on crée
-- une version étendue de la fonction (remplace l'existante).

CREATE OR REPLACE FUNCTION public.transfer_item(
  p_item_type   TEXT,
  p_share_code  TEXT,
  p_to_username TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller_id    UUID := auth.uid();
  v_target_id    UUID;
  v_item_id      UUID;
  v_item_user_id UUID;
BEGIN
  IF v_caller_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated');
  END IF;

  SELECT id INTO v_target_id
  FROM public.profiles
  WHERE lower(username) = lower(trim(p_to_username))
  LIMIT 1;

  IF v_target_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'user_not_found');
  END IF;

  IF v_target_id = v_caller_id THEN
    RETURN jsonb_build_object('ok', false, 'error', 'same_user');
  END IF;

  -- ── CAS : personnage ────────────────────────────────────────
  IF p_item_type = 'char' THEN
    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.characters WHERE share_code = upper(trim(p_share_code)) LIMIT 1;
    IF v_item_id IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'item_not_found'); END IF;
    IF v_item_user_id <> v_caller_id THEN RETURN jsonb_build_object('ok', false, 'error', 'not_owner'); END IF;
    PERFORM public._cleanup_char_tags_on_transfer(v_item_id, v_caller_id);
    DELETE FROM public.followed_characters WHERE character_id = v_item_id AND user_id = v_caller_id;
    DELETE FROM public.followed_characters WHERE character_id = v_item_id AND user_id = v_target_id;
    UPDATE public.characters SET user_id = v_target_id, updated_at = NOW() WHERE id = v_item_id;
    INSERT INTO public.followed_characters (user_id, character_id) VALUES (v_caller_id, v_item_id) ON CONFLICT DO NOTHING;

  -- ── CAS : chronique ─────────────────────────────────────────
  ELSIF p_item_type = 'chr' THEN
    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.chronicles WHERE share_code = upper(trim(p_share_code)) LIMIT 1;
    IF v_item_id IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'item_not_found'); END IF;
    IF v_item_user_id <> v_caller_id THEN RETURN jsonb_build_object('ok', false, 'error', 'not_owner'); END IF;
    DELETE FROM public.followed_chronicles WHERE chronicle_id = v_item_id AND user_id = v_caller_id;
    DELETE FROM public.followed_chronicles WHERE chronicle_id = v_item_id AND user_id = v_target_id;
    UPDATE public.chronicles SET user_id = v_target_id, updated_at = NOW() WHERE id = v_item_id;
    INSERT INTO public.followed_chronicles (user_id, chronicle_id) VALUES (v_caller_id, v_item_id) ON CONFLICT DO NOTHING;

  -- ── CAS : document ──────────────────────────────────────────
  ELSIF p_item_type = 'doc' THEN
    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.documents WHERE share_code = upper(trim(p_share_code)) LIMIT 1;
    IF v_item_id IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'item_not_found'); END IF;
    IF v_item_user_id <> v_caller_id THEN RETURN jsonb_build_object('ok', false, 'error', 'not_owner'); END IF;
    PERFORM public._cleanup_doc_tags_on_transfer(v_item_id, v_caller_id);
    DELETE FROM public.followed_documents WHERE document_id = v_item_id AND user_id = v_caller_id;
    DELETE FROM public.followed_documents WHERE document_id = v_item_id AND user_id = v_target_id;
    UPDATE public.documents SET user_id = v_target_id, updated_at = NOW() WHERE id = v_item_id;
    INSERT INTO public.followed_documents (user_id, document_id) VALUES (v_caller_id, v_item_id) ON CONFLICT DO NOTHING;

  -- ── CAS : campagne ──────────────────────────────────────────
  ELSIF p_item_type = 'campaign' THEN
    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.campaigns WHERE share_code = upper(trim(p_share_code)) LIMIT 1;
    IF v_item_id IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'item_not_found'); END IF;
    IF v_item_user_id <> v_caller_id THEN RETURN jsonb_build_object('ok', false, 'error', 'not_owner'); END IF;
    DELETE FROM public.followed_campaigns WHERE campaign_id = v_item_id AND user_id = v_caller_id;
    DELETE FROM public.followed_campaigns WHERE campaign_id = v_item_id AND user_id = v_target_id;
    UPDATE public.campaigns SET user_id = v_target_id, updated_at = NOW() WHERE id = v_item_id;
    INSERT INTO public.followed_campaigns (user_id, campaign_id) VALUES (v_caller_id, v_item_id) ON CONFLICT DO NOTHING;

  -- ── CAS : couche de carte ────────────────────────────────────
  ELSIF p_item_type = 'map' THEN
    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.map_layers WHERE share_code = upper(trim(p_share_code)) LIMIT 1;
    IF v_item_id IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'item_not_found'); END IF;
    IF v_item_user_id <> v_caller_id THEN RETURN jsonb_build_object('ok', false, 'error', 'not_owner'); END IF;
    -- Transfère la couche ET tous ses marqueurs
    DELETE FROM public.followed_map_layers WHERE layer_id = v_item_id AND user_id = v_caller_id;
    DELETE FROM public.followed_map_layers WHERE layer_id = v_item_id AND user_id = v_target_id;
    UPDATE public.map_layers  SET user_id = v_target_id, updated_at = NOW() WHERE id = v_item_id;
    UPDATE public.map_markers SET user_id = v_target_id, updated_at = NOW() WHERE user_id = v_caller_id;
    INSERT INTO public.followed_map_layers (user_id, layer_id) VALUES (v_caller_id, v_item_id) ON CONFLICT DO NOTHING;

  ELSE
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_type');
  END IF;

  RETURN jsonb_build_object('ok', true, 'item_id', v_item_id, 'to_user_id', v_target_id);
END;
$$;

GRANT EXECUTE ON FUNCTION public.transfer_item(TEXT, TEXT, TEXT) TO authenticated;

-- ══════════════════════════════════════════════════════════════
-- Résumé :
--  • map_layers    : couche partageable (1 par user), avec share_code
--  • followed_map_layers : abonnements joueurs
--  • map_markers RLS étendu pour exposer aux abonnés + anonymes
--  • campaign_items accepte désormais item_type = 'map'
--  • transfer_item étendu pour le type 'map'
-- ══════════════════════════════════════════════════════════════

-- END sql/16_map_sharing.sql

-- ==================================================
-- BEGIN sql/17_multi_map.sql
-- ==================================================
-- ══════════════════════════════════════════════════════════════
-- CAMPLY — Migration : Support multi-cartes
-- À exécuter dans Supabase Dashboard > SQL Editor > New query
-- ══════════════════════════════════════════════════════════════
--
-- Changements :
--  1. Ajout de map_key sur map_markers → lie un marqueur à une
--     carte spécifique du fichier de configuration.
--  2. Ajout de map_key sur map_layers → une couche partageable
--     par carte (et non plus une seule couche par utilisateur).
--  3. Suppression de UNIQUE(user_id) sur map_layers, remplacée
--     par UNIQUE(user_id, map_key).
--  4. Mise à jour de transfer_item pour transférer uniquement
--     les marqueurs de la carte concernée.
-- ══════════════════════════════════════════════════════════════


-- ── 1. Colonne map_key sur map_markers ───────────────────────
-- 'default' pour les marqueurs existants (compatibilité).

ALTER TABLE public.map_markers
  ADD COLUMN IF NOT EXISTS map_key TEXT NOT NULL DEFAULT 'default';

CREATE INDEX IF NOT EXISTS map_markers_user_map_idx
  ON public.map_markers(user_id, map_key);


-- ── 2. Colonne map_key sur map_layers ────────────────────────

ALTER TABLE public.map_layers
  ADD COLUMN IF NOT EXISTS map_key TEXT NOT NULL DEFAULT 'default';

-- Supprime l'ancienne contrainte UNIQUE(user_id)
ALTER TABLE public.map_layers
  DROP CONSTRAINT IF EXISTS map_layers_user_id_key;

-- Nouvelle contrainte : une couche par utilisateur par carte
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'map_layers_user_id_map_key_key'
      AND conrelid = 'public.map_layers'::regclass
  ) THEN
    ALTER TABLE public.map_layers
      ADD CONSTRAINT map_layers_user_id_map_key_key UNIQUE (user_id, map_key);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS map_layers_map_key_idx
  ON public.map_layers(map_key);


-- ── 3. Mise à jour transfer_item — type 'map' ─────────────────
-- Transfert uniquement les marqueurs de la carte concernée
-- (et non plus TOUS les marqueurs de l'utilisateur).

CREATE OR REPLACE FUNCTION public.transfer_item(
  p_item_type   TEXT,
  p_share_code  TEXT,
  p_to_username TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller_id    UUID := auth.uid();
  v_target_id    UUID;
  v_item_id      UUID;
  v_item_user_id UUID;
  v_map_key      TEXT;
BEGIN

  IF v_caller_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated');
  END IF;

  SELECT id INTO v_target_id
  FROM public.profiles
  WHERE lower(username) = lower(trim(p_to_username))
  LIMIT 1;

  IF v_target_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'user_not_found');
  END IF;

  IF v_target_id = v_caller_id THEN
    RETURN jsonb_build_object('ok', false, 'error', 'same_user');
  END IF;

  -- ── CAS : personnage ────────────────────────────────────────
  IF p_item_type = 'char' THEN
    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.characters WHERE share_code = upper(trim(p_share_code)) LIMIT 1;
    IF v_item_id IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'item_not_found'); END IF;
    IF v_item_user_id <> v_caller_id THEN RETURN jsonb_build_object('ok', false, 'error', 'not_owner'); END IF;
    PERFORM public._cleanup_char_tags_on_transfer(v_item_id, v_caller_id);
    DELETE FROM public.followed_characters WHERE character_id = v_item_id AND user_id = v_caller_id;
    DELETE FROM public.followed_characters WHERE character_id = v_item_id AND user_id = v_target_id;
    UPDATE public.characters SET user_id = v_target_id, updated_at = NOW() WHERE id = v_item_id;
    INSERT INTO public.followed_characters (user_id, character_id) VALUES (v_caller_id, v_item_id) ON CONFLICT DO NOTHING;

  -- ── CAS : chronique ─────────────────────────────────────────
  ELSIF p_item_type = 'chr' THEN
    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.chronicles WHERE share_code = upper(trim(p_share_code)) LIMIT 1;
    IF v_item_id IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'item_not_found'); END IF;
    IF v_item_user_id <> v_caller_id THEN RETURN jsonb_build_object('ok', false, 'error', 'not_owner'); END IF;
    DELETE FROM public.followed_chronicles WHERE chronicle_id = v_item_id AND user_id = v_caller_id;
    DELETE FROM public.followed_chronicles WHERE chronicle_id = v_item_id AND user_id = v_target_id;
    UPDATE public.chronicles SET user_id = v_target_id, updated_at = NOW() WHERE id = v_item_id;
    INSERT INTO public.followed_chronicles (user_id, chronicle_id) VALUES (v_caller_id, v_item_id) ON CONFLICT DO NOTHING;

  -- ── CAS : document ──────────────────────────────────────────
  ELSIF p_item_type = 'doc' THEN
    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.documents WHERE share_code = upper(trim(p_share_code)) LIMIT 1;
    IF v_item_id IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'item_not_found'); END IF;
    IF v_item_user_id <> v_caller_id THEN RETURN jsonb_build_object('ok', false, 'error', 'not_owner'); END IF;
    PERFORM public._cleanup_doc_tags_on_transfer(v_item_id, v_caller_id);
    DELETE FROM public.followed_documents WHERE document_id = v_item_id AND user_id = v_caller_id;
    DELETE FROM public.followed_documents WHERE document_id = v_item_id AND user_id = v_target_id;
    UPDATE public.documents SET user_id = v_target_id, updated_at = NOW() WHERE id = v_item_id;
    INSERT INTO public.followed_documents (user_id, document_id) VALUES (v_caller_id, v_item_id) ON CONFLICT DO NOTHING;

  -- ── CAS : campagne ──────────────────────────────────────────
  ELSIF p_item_type = 'campaign' THEN
    SELECT id, user_id INTO v_item_id, v_item_user_id
    FROM public.campaigns WHERE share_code = upper(trim(p_share_code)) LIMIT 1;
    IF v_item_id IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'item_not_found'); END IF;
    IF v_item_user_id <> v_caller_id THEN RETURN jsonb_build_object('ok', false, 'error', 'not_owner'); END IF;
    DELETE FROM public.followed_campaigns WHERE campaign_id = v_item_id AND user_id = v_caller_id;
    DELETE FROM public.followed_campaigns WHERE campaign_id = v_item_id AND user_id = v_target_id;
    UPDATE public.campaigns SET user_id = v_target_id, updated_at = NOW() WHERE id = v_item_id;
    INSERT INTO public.followed_campaigns (user_id, campaign_id) VALUES (v_caller_id, v_item_id) ON CONFLICT DO NOTHING;

  -- ── CAS : couche de carte ────────────────────────────────────
  ELSIF p_item_type = 'map' THEN
    SELECT id, user_id, map_key INTO v_item_id, v_item_user_id, v_map_key
    FROM public.map_layers WHERE share_code = upper(trim(p_share_code)) LIMIT 1;
    IF v_item_id IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'item_not_found'); END IF;
    IF v_item_user_id <> v_caller_id THEN RETURN jsonb_build_object('ok', false, 'error', 'not_owner'); END IF;
    DELETE FROM public.followed_map_layers WHERE layer_id = v_item_id AND user_id = v_caller_id;
    DELETE FROM public.followed_map_layers WHERE layer_id = v_item_id AND user_id = v_target_id;
    -- Transfère uniquement les marqueurs de la carte concernée
    UPDATE public.map_markers
      SET user_id = v_target_id, updated_at = NOW()
      WHERE user_id = v_caller_id AND map_key = v_map_key;
    UPDATE public.map_layers
      SET user_id = v_target_id, updated_at = NOW()
      WHERE id = v_item_id;
    INSERT INTO public.followed_map_layers (user_id, layer_id) VALUES (v_caller_id, v_item_id) ON CONFLICT DO NOTHING;

  ELSE
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_type');
  END IF;

  RETURN jsonb_build_object('ok', true, 'item_id', v_item_id, 'to_user_id', v_target_id);
END;
$$;

GRANT EXECUTE ON FUNCTION public.transfer_item(TEXT, TEXT, TEXT) TO authenticated;

-- ══════════════════════════════════════════════════════════════
-- Résumé :
--  • map_markers.map_key → identifie quelle carte (défaut 'default')
--  • map_layers.map_key  → une couche par carte par utilisateur
--  • UNIQUE(user_id, map_key) remplace UNIQUE(user_id)
--  • transfer_item 'map' ne transfère que les marqueurs de la
--    carte concernée, pas tous les marqueurs de l'utilisateur
--
-- Note : les marqueurs et couches existants reçoivent map_key
-- = 'default'. Assurez-vous que la première entrée de votre
-- MAP_CONFIG.maps a key: 'default', ou remplacez les valeurs
-- avec : UPDATE map_markers SET map_key = 'votre_cle';
-- ══════════════════════════════════════════════════════════════

-- END sql/17_multi_map.sql

-- ══════════════════════════════════════════════════════════════
-- Camply — Read markers persistants (DB)
-- Stocke l'état lu/non-lu par utilisateur pour contenus suivis.
-- ══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.read_markers (
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content_type TEXT NOT NULL CHECK (content_type IN ('character', 'document', 'chronicle', 'chronicle_entry')),
  content_id   UUID NOT NULL,
  parent_id    UUID,
  read_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, content_type, content_id)
);

CREATE INDEX IF NOT EXISTS read_markers_user_idx ON public.read_markers(user_id);
CREATE INDEX IF NOT EXISTS read_markers_parent_idx ON public.read_markers(parent_id) WHERE parent_id IS NOT NULL;

ALTER TABLE public.read_markers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read_markers_select_own" ON public.read_markers;
CREATE POLICY "read_markers_select_own"
  ON public.read_markers FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "read_markers_insert_own" ON public.read_markers;
CREATE POLICY "read_markers_insert_own"
  ON public.read_markers FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "read_markers_update_own" ON public.read_markers;
CREATE POLICY "read_markers_update_own"
  ON public.read_markers FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "read_markers_delete_own" ON public.read_markers;
CREATE POLICY "read_markers_delete_own"
  ON public.read_markers FOR DELETE
  USING (auth.uid() = user_id);
